name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update package list for i386
      run: sudo dpkg --add-architecture i386 && sudo apt-get -y update
    - name: Install packages
      run: sudo apt-get -y install build-essential g++-multilib gcc-mingw-w64 g++-mingw-w64
    - name: test
      run: CXX="g++" make test
    - name: cleanup 0
      run: git clean -xdf
    - name: make
      run: CC="gcc -m32" CXX="g++ -m32" AR="ar rc" RANLIB="ranlib" make
    - name: cleanup 1
      run: git clean -xdf
    - name: make win32
      run: make OSTYPE=win32
    - name: cleanup 2
      run: git clean -xdf
